package com.zhong.kite.model;

import java.util.Date;

public class HaClaimCaseLevelDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.report_no
     *
     * @mbggenerated
     */
    private String reportNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.extra_info
     *
     * @mbggenerated
     */
    private String extraInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.gmt_created
     *
     * @mbggenerated
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.claim_id
     *
     * @mbggenerated
     */
    private Long claimId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.insured_name
     *
     * @mbggenerated
     */
    private String insuredName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.insured_id
     *
     * @mbggenerated
     */
    private Long insuredId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.applicant
     *
     * @mbggenerated
     */
    private String applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.applicant_id
     *
     * @mbggenerated
     */
    private Long applicantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.policy_product_name
     *
     * @mbggenerated
     */
    private String policyProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.policy_product_id
     *
     * @mbggenerated
     */
    private Long policyProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.policy_no
     *
     * @mbggenerated
     */
    private String policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.policy_id
     *
     * @mbggenerated
     */
    private Long policyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_case_level.report_date
     *
     * @mbggenerated
     */
    private Date reportDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.id
     *
     * @return the value of ha_claim_case_level.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.id
     *
     * @param id the value for ha_claim_case_level.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.report_no
     *
     * @return the value of ha_claim_case_level.report_no
     *
     * @mbggenerated
     */
    public String getReportNo() {
        return reportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.report_no
     *
     * @param reportNo the value for ha_claim_case_level.report_no
     *
     * @mbggenerated
     */
    public void setReportNo(String reportNo) {
        this.reportNo = reportNo == null ? null : reportNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.score
     *
     * @return the value of ha_claim_case_level.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.score
     *
     * @param score the value for ha_claim_case_level.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.level
     *
     * @return the value of ha_claim_case_level.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.level
     *
     * @param level the value for ha_claim_case_level.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.extra_info
     *
     * @return the value of ha_claim_case_level.extra_info
     *
     * @mbggenerated
     */
    public String getExtraInfo() {
        return extraInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.extra_info
     *
     * @param extraInfo the value for ha_claim_case_level.extra_info
     *
     * @mbggenerated
     */
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo == null ? null : extraInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.creator
     *
     * @return the value of ha_claim_case_level.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.creator
     *
     * @param creator the value for ha_claim_case_level.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.gmt_created
     *
     * @return the value of ha_claim_case_level.gmt_created
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.gmt_created
     *
     * @param gmtCreated the value for ha_claim_case_level.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.modifier
     *
     * @return the value of ha_claim_case_level.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.modifier
     *
     * @param modifier the value for ha_claim_case_level.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.gmt_modified
     *
     * @return the value of ha_claim_case_level.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.gmt_modified
     *
     * @param gmtModified the value for ha_claim_case_level.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.is_deleted
     *
     * @return the value of ha_claim_case_level.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.is_deleted
     *
     * @param isDeleted the value for ha_claim_case_level.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.claim_id
     *
     * @return the value of ha_claim_case_level.claim_id
     *
     * @mbggenerated
     */
    public Long getClaimId() {
        return claimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.claim_id
     *
     * @param claimId the value for ha_claim_case_level.claim_id
     *
     * @mbggenerated
     */
    public void setClaimId(Long claimId) {
        this.claimId = claimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.insured_name
     *
     * @return the value of ha_claim_case_level.insured_name
     *
     * @mbggenerated
     */
    public String getInsuredName() {
        return insuredName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.insured_name
     *
     * @param insuredName the value for ha_claim_case_level.insured_name
     *
     * @mbggenerated
     */
    public void setInsuredName(String insuredName) {
        this.insuredName = insuredName == null ? null : insuredName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.insured_id
     *
     * @return the value of ha_claim_case_level.insured_id
     *
     * @mbggenerated
     */
    public Long getInsuredId() {
        return insuredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.insured_id
     *
     * @param insuredId the value for ha_claim_case_level.insured_id
     *
     * @mbggenerated
     */
    public void setInsuredId(Long insuredId) {
        this.insuredId = insuredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.applicant
     *
     * @return the value of ha_claim_case_level.applicant
     *
     * @mbggenerated
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.applicant
     *
     * @param applicant the value for ha_claim_case_level.applicant
     *
     * @mbggenerated
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.applicant_id
     *
     * @return the value of ha_claim_case_level.applicant_id
     *
     * @mbggenerated
     */
    public Long getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.applicant_id
     *
     * @param applicantId the value for ha_claim_case_level.applicant_id
     *
     * @mbggenerated
     */
    public void setApplicantId(Long applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.policy_product_name
     *
     * @return the value of ha_claim_case_level.policy_product_name
     *
     * @mbggenerated
     */
    public String getPolicyProductName() {
        return policyProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.policy_product_name
     *
     * @param policyProductName the value for ha_claim_case_level.policy_product_name
     *
     * @mbggenerated
     */
    public void setPolicyProductName(String policyProductName) {
        this.policyProductName = policyProductName == null ? null : policyProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.policy_product_id
     *
     * @return the value of ha_claim_case_level.policy_product_id
     *
     * @mbggenerated
     */
    public Long getPolicyProductId() {
        return policyProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.policy_product_id
     *
     * @param policyProductId the value for ha_claim_case_level.policy_product_id
     *
     * @mbggenerated
     */
    public void setPolicyProductId(Long policyProductId) {
        this.policyProductId = policyProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.policy_no
     *
     * @return the value of ha_claim_case_level.policy_no
     *
     * @mbggenerated
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.policy_no
     *
     * @param policyNo the value for ha_claim_case_level.policy_no
     *
     * @mbggenerated
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo == null ? null : policyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.policy_id
     *
     * @return the value of ha_claim_case_level.policy_id
     *
     * @mbggenerated
     */
    public Long getPolicyId() {
        return policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.policy_id
     *
     * @param policyId the value for ha_claim_case_level.policy_id
     *
     * @mbggenerated
     */
    public void setPolicyId(Long policyId) {
        this.policyId = policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_case_level.report_date
     *
     * @return the value of ha_claim_case_level.report_date
     *
     * @mbggenerated
     */
    public Date getReportDate() {
        return reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_case_level.report_date
     *
     * @param reportDate the value for ha_claim_case_level.report_date
     *
     * @mbggenerated
     */
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }
}