package com.zhong.kite.dao;


import com.zhong.kite.model.HaClaimCaseLevelDO;

public interface HaClaimCaseLevelDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ha_claim_case_level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ha_claim_case_level
     *
     * @mbggenerated
     */
    int insert(HaClaimCaseLevelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ha_claim_case_level
     *
     * @mbggenerated
     */
    int insertSelective(HaClaimCaseLevelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ha_claim_case_level
     *
     * @mbggenerated
     */
    HaClaimCaseLevelDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ha_claim_case_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HaClaimCaseLevelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ha_claim_case_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HaClaimCaseLevelDO record);

}