package com.zhong.kite.model;

import java.util.Date;

public class HaPreclaimAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.preclaim_attachment_no
     *
     * @mbggenerated
     */
    private String preclaimAttachmentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.gmt_created
     *
     * @mbggenerated
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_preclaim_attachment.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.id
     *
     * @return the value of ha_preclaim_attachment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.id
     *
     * @param id the value for ha_preclaim_attachment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.name
     *
     * @return the value of ha_preclaim_attachment.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.name
     *
     * @param name the value for ha_preclaim_attachment.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.type
     *
     * @return the value of ha_preclaim_attachment.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.type
     *
     * @param type the value for ha_preclaim_attachment.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.description
     *
     * @return the value of ha_preclaim_attachment.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.description
     *
     * @param description the value for ha_preclaim_attachment.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.preclaim_attachment_no
     *
     * @return the value of ha_preclaim_attachment.preclaim_attachment_no
     *
     * @mbggenerated
     */
    public String getPreclaimAttachmentNo() {
        return preclaimAttachmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.preclaim_attachment_no
     *
     * @param preclaimAttachmentNo the value for ha_preclaim_attachment.preclaim_attachment_no
     *
     * @mbggenerated
     */
    public void setPreclaimAttachmentNo(String preclaimAttachmentNo) {
        this.preclaimAttachmentNo = preclaimAttachmentNo == null ? null : preclaimAttachmentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.is_deleted
     *
     * @return the value of ha_preclaim_attachment.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.is_deleted
     *
     * @param isDeleted the value for ha_preclaim_attachment.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.gmt_created
     *
     * @return the value of ha_preclaim_attachment.gmt_created
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.gmt_created
     *
     * @param gmtCreated the value for ha_preclaim_attachment.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.gmt_modified
     *
     * @return the value of ha_preclaim_attachment.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.gmt_modified
     *
     * @param gmtModified the value for ha_preclaim_attachment.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.creator
     *
     * @return the value of ha_preclaim_attachment.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.creator
     *
     * @param creator the value for ha_preclaim_attachment.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_preclaim_attachment.modifier
     *
     * @return the value of ha_preclaim_attachment.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_preclaim_attachment.modifier
     *
     * @param modifier the value for ha_preclaim_attachment.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}